name: fluttersaurus
description: A Flutter thesaurus made for Byteconf Flutter 2020.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.3
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  google_fonts: ^1.1.0
  rxdart: ^0.24.0
  shimmer: ^1.1.1
  thesaurus_repository:
    path: packages/thesaurus_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.0.0
  flutter_launcher_icons: ^0.7.5
  mockito: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
